apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
  labels:
    app: myapp
    tier: frontend
spec:
  # modify number of replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  #template of the pod
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
          - containerPort: 80